name: rc_controller
description: "Flutter app to controller esp8266 in an RC Car"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.3
  syncfusion_flutter_sliders: ^30.2.5
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5+1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

